#cloud-config
hostname: omega-master
timezone: Asia/Taipei
manage_etc_hosts: true

bootcmd:
  - mkdir -p /etc/ssh/sshd_config.d/
  - echo 'Port 433' > /etc/ssh/sshd_config.d/omega_port.conf

users:
  - default
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBebBg8k8yKOCnh3rzJKkFNA3QbPOIhUtPNJsPMglADhhvyOBDJuNlX6n1OASgP0mcXtK82xEXT6Zge/pOTQc0NwBRKxNzj08iYB9NggkWVVmCVjMym4uvdhwUC+uocSRr+W58trxj/Z78YFJs8cwyC67qJRJHtQQ9f8FiXImPBiUJ3NdxtxjTCTpXr1TM2/r3eKnMUoZHS9mGom6yGU2R313KDpZ6Gwy7Br+NvtfkKlDu0uYEoi6awqLQBZW/DTDv8fj1ChqH5fJZN4kuOwR0wE3uaQO22tKDVkOX2IpaiaAFPz6fnCuGYs4XEJYAUU5+0mrgM6PdF/F+u6VlURTl hung@soulos

package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - unzip
  - curl
  - wget
  - net-tools
  - htop
  - ufw
  - fail2ban
  - openssh-server
  - lsof
  - tmux
  - neofetch
  - nano

write_files:
  - path: /etc/ssh/sshd_config.d/omega_port.conf
    content: |
      Port 433
      AddressFamily any
      ListenAddress 0.0.0.0
      PermitRootLogin no
      PasswordAuthentication no
      AllowUsers ubuntu
      ClientAliveInterval 300
      ClientAliveCountMax 2

  - path: /home/ubuntu/.bash_aliases
    content: |
      alias ll='ls -alF'
      alias gs='git status'
      alias gl='git log --oneline --graph --decorate'
      alias py='python3'
      alias ports='sudo lsof -i -P -n | grep LISTEN'
      alias monitor='htop'
      alias omega='neofetch && echo "🚀 WELCOME TO OMEGA MASTER NODE"'

  - path: /home/ubuntu/.bashrc
    append: true
    content: |
      export OMEGA_NODE_ROLE="master"
      export OMEGA_STAGE="deploying"
      echo "🔁 Omega 環境載入完成。"

  - path: /home/ubuntu/README-OMEGA.txt
    content: |
      🌌 Omega Master 節點啟動成功
      - SSH Port: 433
      - 使用者: ubuntu
      - 狀態：所有必要環境已部署完成
      📜 輸入 `omega` 啟動 CLI 驗證介面

runcmd:
  - echo "🔒 Initializing SSH environment..."
  - systemctl daemon-reexec
  - systemctl enable ssh
  - systemctl restart ssh
  - echo "🔐 SSH running on port 433" > /home/ubuntu/ssh_ready.txt
  - ufw allow 433/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow OpenSSH
  - ufw --force enable
  - touch /home/ubuntu/omega_ready.flag
  - chown ubuntu:ubuntu /home/ubuntu/*
  - chmod +x /home/ubuntu/.bash_aliases
  - echo "✅ Omega Init Finished" > /home/ubuntu/init_status.log

final_message: "✅ Omega Master Node 設定完成，請使用 ssh -p 433 ubuntu@<your_ip> 登入"

power_state:
  mode: reboot
  message: Rebooting after cloud-init
  timeout: 30
  condition: true

